version: "3.7"

services:
  apache:
    image: "bitnami/apache:latest"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./apache.conf:/opt/bitnami/apache/conf/httpd.conf
      - ./apache.html:/opt/bitnami/apache/htdocs/index.html

  ihs:
    image: "bitnami/apache:latest"
    ports:
      - "81:8080"
      - "444:8443"
    volumes:
      - ./ihs.conf:/opt/bitnami/apache/conf/httpd.conf
      - ./ihs.html:/opt/bitnami/apache/htdocs/index.html
